name: Build Create Stencil CLI

on:
  workflow_call:
  # Make this a reusable workflow, no value needed
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows

jobs:
  build_cli:
    name: 🏗️ Build CLI
    runs-on: 'ubuntu-latest'
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          # the pull_request_target event will consider the HEAD of `main` to be the SHA to use.
          # attempt to use the SHA associated with a pull request and fallback to HEAD of `main`
          ref: ${{ github.event_name == 'pull_request_target' && format('refs/pull/{0}/merge', github.event.number) || '' }}
          persist-credentials: false

      - name: 🕸️ Get Core Dependencies
        uses: stenciljs/.github/actions/get-core-dependencies@main

      - name: 🟩 Setup Node 20.15.1
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.1
          cache: 'npm'

      - name: 📦 Clean install on Linux (resolve native optional deps)
        run: |
          rm -rf node_modules package-lock.json
          npm install --no-audit --no-fund
        shell: bash

      - name: 🏗️ CLI Build
        run: npm run build
        shell: bash

      - name: 🧪 Unit Tests
        run: npm test
        shell: bash

      - name: 📤 Upload Build Artifacts
        uses: stenciljs/.github/actions/upload-archive@main
        with:
          paths: index.js
